Installing the dependencies
=============================


In [ ]:
pip install tensorflow_text

     |████████████████████████████████| 4.9 MB 5.5 MB/s 
     |████████████████████████████████| 462 kB 36.0 MB/s 


Import the tensorflow hub and text module to process the texts.

In [ ]:
import tensorflow_hub as hub
import tensorflow_text as text

Load the preporcessing and encoder url in the snippet

In [ ]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

Check for the BERT module if it is working fine and generating the feature vectors

In [ ]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [ ]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
bert_model = hub.KerasLayer(encoder_url)

In [ ]:
bert_results = bert_model(text_preprocessed)

In [ ]:
bert_results.keys()

dict_keys(['pooled_output', 'default', 'sequence_output', 'encoder_outputs'])

In [ ]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292038,  0.08567842,  0.14476822, ..., -0.09677143,
          0.08722145,  0.07711081],
        [ 0.17839344, -0.19006258,  0.5034949 , ..., -0.0586981 ,
          0.32717144, -0.15578583],
        [ 0.18701449, -0.43388814, -0.48875296, ..., -0.15502766,
          0.00145172, -0.2447103 ],
        ...,
        [ 0.12083013,  0.12884311,  0.4645362 , ...,  0.07375546,
          0.17441897,  0.16522236],
        [ 0.07967884, -0.01190644,  0.5022541 , ...,  0.13777748,
          0.210022  ,  0.00624548],
        [-0.07212698, -0.28303394,  0.5903344 , ...,  0.4755187 ,
          0.1666846 , -0.08920381]],

       [[-0.07900536,  0.36335137, -0.21101594, ..., -0.171837  ,
          0.16299717,  0.6724262 ],
        [ 0.27883533,  0.43716228, -0.35764885, ..., -0.04463524,
          0.38315073,  0.58879745],
        [ 1.2037673 ,  1.072702  ,  0.48408717, ...,  0.24921033,
          0.4073103 ,  0.4048179 ],
        ...,

In [ ]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177463, -0.21411951,  0.49769327, ...,  0.24465072,
        -0.47334516,  0.81758744],
       [-0.91712326, -0.4793521 , -0.78657013, ..., -0.617518  ,
        -0.71026915,  0.92184293]], dtype=float32)>

In [ ]:
len(bert_results['encoder_outputs'])

12

In [ ]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

In [ ]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901425,  0.00644732, -0.03614959, ...,  0.04999626,
           0.06149194, -0.02657545],
         [ 1.1753378 ,  1.2140784 ,  1.1569978 , ...,  0.11634377,
          -0.3585534 , -0.4049019 ],
         [ 0.03859021,  0.5386997 , -0.21089756, ...,  0.21858235,
           0.7260173 , -1.1158612 ],
         ...,
         [-0.07587024, -0.25421894,  0.7075514 , ...,  0.505419  ,
          -0.1887869 ,  0.15028353],
         [-0.1606659 , -0.28089708,  0.5759705 , ...,  0.5275857 ,
          -0.11141351,  0.02887536],
         [-0.04428169, -0.2027955 ,  0.5909354 , ...,  0.8133834 ,
          -0.3907574 , -0.02601734]],
 
        [[ 0.18903583,  0.02752563, -0.06513733, ..., -0.006202  ,
           0.15053886,  0.03165463],
         [ 0.59161484,  0.7589136 , -0.07240709, ...,  0.6190397 ,
           0.8292891 ,  0.16161957],
         [ 1.446081  ,  0.4460263 ,  0.40990278, ...,  0.48255885,
           0.6269118 ,  0.13

Preprocessing data for the BERT Model



In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

Display first 5 data of the loaded dataset

In [ ]:
import pandas as pd

df = pd.read_csv("train/Constraint_Train.csv")
print(df.shape)
df.head(5)

(6420, 3)


id                                              tweet label
0   1  The CDC currently reports 99031 deaths. In gen...  real
1   2  States reported 1121 deaths a small rise from ...  real
2   3  Politically Correct Woman (Almost) Uses Pandem...  fake
3   4  #IndiaFightsCorona: We have 1524 #COVID testin...  real
4   5  Populous states can generate large case counts...  real

Group the elements by the label of the news dataset

In [ ]:
df.groupby('label').describe()

id                                                                 
        count         mean          std  min      25%     50%      75%     max
label                                                                         
fake   3060.0  3242.197712  1839.883860  3.0  1656.50  3234.5  4842.00  6419.0
real   3360.0  3181.632440  1865.502613  1.0  1561.75  3172.5  4788.25  6420.0

Assign label 

In [ ]:
def f(x):
    return {
        'fake': 0,
        'real': 1,
    }[x]

df['label_rep']=df['label'].apply(lambda x: f(x))
df.sample(10)

id                                              tweet label  label_rep
5710  5711  Temperature, humidity could affect transmissio...  fake          0
4997  4998  Japanese Nobel laureate Tasuku Honjo who worke...  fake          0
4047  4048  I'm running a fever again. Been suffering from...  fake          0
2017  2018  Groups of pupils should only be sent home if t...  real          1
4536  4537  ???The CDC may have to stop calling COVID-19 a...  fake          0
4139  4140  Says this poem about people staying home was w...  fake          0
6227  6228  A popular YouTube video is claiming coronaviru...  fake          0
4039  4040  Do you have questions about #COVID19? Find ans...  real          1
5181  5182  @ricci_sergienko All that stuff should be comi...  real          1
3184  3185  Russian president Vladimir Putin released 800 ...  fake          0

BERT APPROACH
==============


Load Bert process in the code to train with the csv dataset file

In [ ]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [ ]:
X_train, y_train = df["tweet"], df["label_rep"]

In [ ]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer_2 (KerasLayer)     {'input_type_ids':   0           ['text[0][0]']                   
                                (None, 128),                                                      
                                 'input_word_ids':                                                
                                (None, 128),                                                      
                                 'input_mask': (Non                                               
                                e, 128)}                                                      

In [ ]:
METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=METRICS)

model.fit(X_train, y_train, epochs=10)

Epoch 1/10
201/201 [==============================] - 153s 695ms/step - loss: 0.5897 - accuracy: 0.6919 - precision: 0.6811 - recall: 0.7735
Epoch 2/10
201/201 [==============================] - 139s 691ms/step - loss: 0.4905 - accuracy: 0.7759 - precision: 0.7488 - recall: 0.8604
Epoch 3/10
201/201 [==============================] - 139s 690ms/step - loss: 0.4421 - accuracy: 0.8087 - precision: 0.7736 - recall: 0.8970
Epoch 4/10
201/201 [==============================] - 139s 690ms/step - loss: 0.4137 - accuracy: 0.8265 - precision: 0.7946 - recall: 0.9015
Epoch 5/10
201/201 [==============================] - 139s 690ms/step - loss: 0.3904 - accuracy: 0.8422 - precision: 0.8092 - recall: 0.9140
Epoch 6/10
201/201 [==============================] - 139s 689ms/step - loss: 0.3745 - accuracy: 0.8475 - precision: 0.8165 - recall: 0.9140
Epoch 7/10
201/201 [==============================] - 138s 689ms/step - loss: 0.3599 - accuracy: 0.8565 - precision: 0.8274 - recall: 0.9173
Epoch 8/10
20

In [ ]:
df_t = pd.read_csv("val/Constraint_Val.csv")
print(df_t.shape)
df_t.head(5)

(2140, 3)


id                                              tweet label
0   1  Chinese converting to Islam after realising th...  fake
1   2  11 out of 13 people (from the Diamond Princess...  fake
2   3  COVID-19 Is Caused By A Bacterium, Not Virus A...  fake
3   4  Mike Pence in RNC speech praises Donald Trump’...  fake
4   5  6/10 Sky's @EdConwaySky explains the latest #C...  real

In [ ]:
df_t.groupby('label').describe()

id                                                               
        count         mean         std  min     25%     50%      75%     max
label                                                                       
fake   1020.0  1087.805882  627.831667  1.0  540.00  1087.5  1637.50  2139.0
real   1120.0  1054.739286  608.584391  5.0  533.75  1060.5  1578.25  2140.0

In [ ]:
df_t['label_rep']=df_t['label'].apply(lambda x: f(x))
df_t.sample(10)

id                                              tweet label  label_rep
1471  1472  A doctor died in Colombia after curing 6 patie...  fake          0
1680  1681  The Duchess of Cambridge has praised mothers o...  real          1
270    271  “Nearly half of (Missouri) counties have not r...  fake          0
249    250  Indian's Ruling party BJP-run state Manipur is...  fake          0
1732  1733  Avoid the 3️⃣ Cs. There are certain places whe...  real          1
1641  1642  The China virus Covid-19 is a Soros/Globalists...  fake          0
1588  1589  Indian State of Kerala's government is paying ...  fake          0
543    544  RT @WHO: All over the 🌎🌍🌏 #healthworkers are f...  real          1
1982  1983  If a patient is diagnosed with COVID-19 and th...  fake          0
1188  1189  On the 5th Jan days after a cluster of unknown...  real          1

In [ ]:
X_test, y_test = df_t["tweet"], df_t["label_rep"]

In [ ]:
model.evaluate(X_test, y_test)

67/67 [==============================] - 47s 689ms/step - loss: 0.3104 - accuracy: 0.8734 - precision: 0.8471 - recall: 0.9250


[0.3103795051574707, 0.8733645081520081, 0.8470972776412964, 0.925000011920929]

In [ ]:
Predict_test = [
    'A photo shows a 19-year-old vaccine for canine coronavirus that could be used to prevent the new coronavirus causing COVID-19.',
    'ICUs are full forcing #COVID patients to wait “hours and hoursto admit to the emergency room. https://t.co/go6Sx5yuRx',
    'The new coronavirus does not settle in the air but is grounded so it is not transmitted by air.',
    'A WhatsApp forward has gone viral which claimed that a vaccine for coronavirus has been discovered. The viral forward also claims that the treatment for coronavirus is mentioned in India\'s Intermediate Zoology book.',
    '"Sanitizer will do nothing for the coronavirus."'
]

model.predict(Predict_test)

array([[0.0479722 ],
       [0.7977803 ],
       [0.18739243],
       [0.02610618],
       [0.06492506]], dtype=float32)